language: cpp

os: linux
dist: xenial
sudo: required

compiler:
  - clang
  - gcc

env:
  global:
    - CXX_FLAGS="-Wall -pedantic -Werror -Wno-variadic-macros -Wno-long-long -Wno-shadow"

before_script:
  - mkdir build
  - cd build
  - cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} ..

script:
  - cmake --build .

after_script:
  - cmake --build . --target test
