language: cpp

os: linux
dist: xenial
sudo: required

compiler:
  - clang-8
  - gcc-9

env:
  global:
    - CXX_FLAGS="-Wall -pedantic -Werror -Wno-variadic-macros -Wno-long-long -Wno-shadow"

matrix:
  include:

    - name: gcc 9
      os: linux
      dist: xenial
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

    - name: clang 8
      os: linux
      dist: xenial
      sudo: required
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-8
          packages:
            - clang-8
      env:
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - mkdir build
  - cd build
  - cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} ..

script:
  - cmake --build .

after_script:
  - cmake --build . --target test
