version: '1.0.{build}'

os:
  - Visual Studio 2017

platform:
  - Win32
  - x64
 
configuration:
  - Release
  - Debug

install:
  - git submodule update --init --recursive

before_build:
  - cmake -A%PLATFORM% .

build_script:
  - cmake --build .

test_script:
  - ctest -V
